version: '3'
services:
  
  # Database - MariaDB has been chosen, runs on default port
  db:
    container_name: database
    image: mariadb
    volumes:
      - ./db_data/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  
  # Wordpress - FPM-Alpinem default port 9000
  wordpress:
    depends_on:
      - db
    container_name: wordpress
    image: wordpress:fpm-alpine
    restart: always
    volumes: ['./www/:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
 
  # Caddy Web Server      
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
      - ./caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - wpsite
      
  # phpmyadmin - allows simple db migration, runs on port 8788
  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8788:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  
networks:
  wpsite:
volumes:
  db_data:
  www:
  caddy_data: